# Generated by Django 5.0.4 on 2024-04-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=250)),
                ('stu_email', models.EmailField(max_length=254)),
                ('stu_city', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'STudent',
                'db_table': 'Student',
            },
        ),
    ]
